# Generated by Django 5.0.6 on 2024-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_order_status_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En_attente', 'En attente'), ('En cours de livraison', 'En cours de livraison'), ('LivrE', 'Livré')], max_length=200, null=True),
        ),
    ]
