# Generated by Django 5.0.6 on 2024-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours de livraison', 'En cours de livraison'), ('Livré', 'Livré')], max_length=200, null=True),
        ),
    ]
